<html>
    <head>
        <title>TUGAS PERULANGAN FOR</title>
    </head>
<body>


<!-- MENAMPILKAN BILANGAN GENAP 1-20 PAKAI LOOPING (PERULANGAN) FOR, MENAMPILKAN BILANGAN GANJIL 1-20 PAKAI LOOPING (PERULANGAN) FOR, MENAMPILKAN BILANGAN 2 4 8 16 32 64, MENAMPILKAN BILANGAN 3 7 15 31 63 127 -->

<?php

    



?>


</body>
</html>